_core:
  default_config_hash: IgOVnECx6lbVt6JVFnadoEEugneDf3UblPZnOzov43Q
mode: simple
ignored_config_entities:
  - 'search_api.server.dev_algolia:api_key'
  - 'search_api.server.dev_algolia:application_id'
